Functions interface
Intergiro/model-acquirer pull request #182
Opened 2021-09-30 15:39 UTC by nilssonemma

2021-10-01 08:20 UTC, robinnedergard requested changes
(Not a fan of the name functions, but that I guess is what was decided.)
Make a parity branch.

2021-10-01 08:20 UTC, robinnedergard commented on Client/Functions.ts
> +		return await this.connection.patch<ModelFunctions>("merchant/functions", request)
Inconsistent use of <T> and <T | gracely.Error>.

2021-10-04 07:04 UTC, marcushanses approved these changes

2021-10-04 07:34 UTC, robinnedergard approved these changes

2021-10-04 08:17 UTC, fredrikbryntesson approved these changes

2021-10-04 08:17 UTC, merged