Change mock processor to name baboba
intergiro/model-acquirer pull request #221
Opened 2021-11-15 09:49 UTC by Magnus93

2021-11-15 09:55 UTC, robinnedergard requested changes

2021-11-15 09:55 UTC, robinnedergard commented on Merchant/Processor.ts
> +			(value.baboba == undefined || (typeof value.baboba == "object" && typeof value.baboba.reference == "string"))
```suggestion
			(value.baboba == undefined || (typeof value.baboba == "object" && value.baboba && typeof value.baboba.reference == "string"))
```

2021-11-15 14:15 UTC, marcushanses approved these changes

2021-11-15 14:15 UTC, marcushanses commented on Merchant/Processor.ts
> +			(value.baboba == undefined || (typeof value.baboba == "object" && value.baboba && typeof value.baboba.reference == "string"))
'npm run fix' to fix lint error.

2021-11-15 16:09 UTC, Magnus93 commented on Merchant/Processor.ts
> +			(value.baboba == undefined || (typeof value.baboba == "object" && value.baboba && typeof value.baboba.reference == "string"))
Fixed

2021-11-16 17:23 UTC, nilssonemma approved these changes

2021-11-17 08:59 UTC, robinnedergard approved these changes

2021-11-17 09:00 UTC, robinnedergard approved these changes

2021-11-17 11:11 UTC, fredrikbryntesson approved these changes

2021-11-17 11:12 UTC, merged