Added processor parameter in History
intergiro/model-acquirer pull request #234
Opened 2021-12-20 12:40 UTC by nilssonemma

2021-12-22 08:45 UTC, marcushanses approved these changes

2021-12-22 08:45 UTC, marcushanses commented on Authorization/History/Capture.ts
> +		authorization: { number: string; currency: isoly.Currency, processor?: Record<string, any> },
npm run fix

2021-12-23 08:04 UTC, Magnus93 requested changes

2021-12-23 08:04 UTC, Magnus93 commented on State/Authorization.ts
> +		authorization: AcquirerAuthorization
Fix lint warning

2021-12-23 08:04 UTC, Magnus93 commented on Verification/Creatable.ts
> +										'{ type: "pares" | "method" | "challenge" | "guard"; data: string } | { type: "method"; ThreeDSServerTransID: string; timeout: true }',
fix lint warning

2021-12-23 08:33 UTC, Magnus93 approved these changes

2021-12-23 08:44 UTC, Magnus93 approved these changes

2022-01-02 23:00 UTC, fredrikbryntesson approved these changes

2022-01-02 23:00 UTC, merged