Functions
intergiro/model-acquirer pull request #236
Opened 2021-12-22 08:36 UTC by marcushanses

2021-12-23 08:37 UTC, Magnus93 approved these changes

2022-01-03 15:30 UTC, nilssonemma requested changes

2022-01-03 15:30 UTC, nilssonemma commented on Merchant/Rules.ts
> +		if (Rules.is(rules)) {
please remove brackets

2022-01-05 09:37 UTC, fredrikbryntesson approved these changes

2022-01-05 09:37 UTC, merged