Fradio interface
intergiro/model-acquirer pull request #248
Opened 2022-02-02 14:47 UTC by Magnus93

Add fraudio to AuthorizationState, FailedAuthorization, PreAuthorization and model.Authorization

2022-02-02 15:24 UTC, robinnedergard requested changes
Also add parity

2022-02-02 15:24 UTC, robinnedergard commented on Fraudio/index.ts
> +			typeof value == "object" &&
Implicit not null check:
```suggestion
			typeof value == "object" && value &&
```

2022-02-02 15:24 UTC, robinnedergard commented on Fraudio/index.ts
> +	id: authly.Identifier
string, never assume externally provided id:s are dividable by 4 (which authly.Identifier always are)
```suggestion
	id: string
```

2022-02-02 15:24 UTC, robinnedergard commented on Fraudio/index.ts
> +			authly.Identifier.is(value.id) &&
```suggestion
			typeof value.id == "string" &&
```

2022-02-02 15:24 UTC, robinnedergard commented on Fraudio/index.ts
> +	score: number
Original value is actually a string containing a number
```suggestion
	score: string
```

2022-02-02 15:24 UTC, robinnedergard commented on Fraudio/index.ts
> +	threshold: number
Original value is actually a string containing a number
```suggestion
	threshold: string
```

2022-02-02 15:24 UTC, robinnedergard commented on Fraudio/index.ts
> +			typeof value.threshold == "number" &&
```suggestion
			typeof value.threshold == "string" &&
```

2022-02-02 15:24 UTC, robinnedergard commented on Fraudio/index.ts
> +			typeof value.score == "number" &&
```suggestion
			typeof value.score == "string" &&
```

2022-02-02 15:24 UTC, robinnedergard commented on Fraudio/index.ts
> +		score: new selectively.Type.Number(),
```suggestion
		score: new selectively.Type.String(),
```

2022-02-02 15:24 UTC, robinnedergard commented on Fraudio/index.ts
> +		threshold: new selectively.Type.Number(),
```suggestion
		threshold: new selectively.Type.String(),
```

2022-02-02 15:24 UTC, robinnedergard commented on State/Authorization.spec.ts
> +				model: "modelY",
```suggestion
				score: "0.75",
				recommendation: "yellow",
				id: "12345678",
				threshold: "0.5",
				model: "modelY",
```

2022-02-03 07:36 UTC, Magnus93 commented on Fraudio/index.ts
> +	score: number
I'll convert to number in the from function.

2022-02-03 07:38 UTC, Magnus93 commented on Fraudio/index.ts
> +	threshold: number
I'll convert to number in the from function

2022-02-03 07:58 UTC, Magnus93 commented on Fraudio/index.ts
> +			typeof value == "object" &&
Fixed

2022-02-03 08:19 UTC, Magnus93 commented on Authorization/index.ts
> +							value.category == undefined ||
```suggestion
							value.fraudio == undefined ||
```

2022-02-03 12:44 UTC, robinnedergard approved these changes

2022-02-07 08:27 UTC, nilssonemma approved these changes

2022-02-07 10:37 UTC, marcushanses approved these changes

2022-02-08 09:12 UTC, fredrikbryntesson approved these changes

2022-02-08 09:12 UTC, merged