Added authorized to state merchant. Parity.
intergiro/model-acquirer pull request #278
Opened 2022-03-16 13:26 UTC by marcushanses

2022-03-16 15:46 UTC, nilssonemma approved these changes

2022-03-21 00:11 UTC, robinnedergard requested changes

2022-03-21 00:11 UTC, robinnedergard commented on State/Merchant.ts
> +			(value.authorized == undefined || typeof value.fees == "number")
Also create new PR on master and fix this on master:
```suggestion
			(value.authorized == undefined || typeof value.authorized == "number")
```

2022-03-21 08:19 UTC, Magnus93 approved these changes

2022-03-24 10:30 UTC, robinnedergard commented on State/Merchant.ts
> +			(value.authorized == undefined || typeof value.fees == "number")
Yes, I fixed it, needed it fixed

2022-03-24 10:31 UTC, robinnedergard approved these changes

2022-03-28 07:35 UTC, closed without merging