Added soft descriptor to merchant
intergiro/model-acquirer pull request #299
Opened 2022-04-05 14:29 UTC by nilssonemma

2022-04-05 14:34 UTC, robinnedergard requested changes
Also: State/Merchant.ts#L47 github actions report a type error

2022-04-05 14:34 UTC, robinnedergard commented on Merchant/index.ts
> +				(typeof value.descriptor == "object" &&
```suggestion
				(typeof value.descriptor == "object" &&
				value.descriptor &&
```

2022-04-05 14:34 UTC, robinnedergard commented on Merchant/index.ts
> +				(typeof value.descriptor == "object" &&
avoid null

2022-04-05 14:34 UTC, robinnedergard commented on Merchant/index.ts
> +								(typeof value.descriptor == "object" &&
```suggestion
								(typeof value.descriptor == "object" &&
								value.descriptor &&
```

2022-04-05 14:34 UTC, robinnedergard commented on Merchant/index.ts
> +	export function getDecriptor(merchant: Merchant): string | undefined {
```suggestion
	export function getDescriptor(merchant: Merchant): string | undefined {
```

2022-04-06 08:56 UTC, fredrikbryntesson approved these changes

2022-04-06 08:56 UTC, merged