Fixed refund fee fix
intergiro/model-acquirer pull request #305
Opened 2022-04-13 14:06 UTC by marcushanses

2022-04-14 11:39 UTC, Magnus93 requested changes

2022-04-14 11:39 UTC, Magnus93 commented on Merchant/Fee/index.ts
> +		return !!refundDate && !!refunded && !!captured && refunded == captured
I'm not convinced that `refunded == captured` will always work like you expect with floating point numbers, since an exact match is needed. This would work if you are dealing with minor units (integers), but not floating point.

I think checking if it's within ±0.5 minor units (öre/cent) should work.

Maybe we can add a `Currency.equals` function in isoly
``` ts
function equals(currency: Currency, amount1: number, amount2: number): boolean 
```

2022-04-14 11:56 UTC, Magnus93 approved these changes

2022-04-14 11:56 UTC, Magnus93 commented on Merchant/Fee/index.ts
> +		return !!refundDate && !!refunded && !!captured && refunded == captured
Never mind. I tested adding up a bunch of uneven numbers with the Currency.add in isoly, and it seams to work as intended.

2022-04-14 11:58 UTC, marcushanses commented on Merchant/Fee/index.ts
> +		return !!refundDate && !!refunded && !!captured && refunded == captured
:+1:

2022-04-14 13:05 UTC, Magnus93 commented on Merchant/Fee/index.ts
> +					  ) ?? 0
Why are you not using `gross`, then it's a totalRefund?

2022-04-20 07:27 UTC, marcushanses commented on Merchant/Fee/index.ts
> +					  ) ?? 0
Because the gross might not be the full value.

2022-04-20 07:35 UTC, marcushanses commented on Merchant/Fee/index.ts
> +					  ) ?? 0
It's better to use the actual amount of all refunds than to assume that the last refund is the total amount.

2022-04-20 09:17 UTC, nilssonemma approved these changes

2022-04-20 09:19 UTC, robinnedergard approved these changes

2022-04-20 12:35 UTC, fredrikbryntesson approved these changes

2022-04-20 12:35 UTC, merged