Fee restructure
intergiro/model-acquirer pull request #306
Opened 2022-04-14 13:15 UTC by marcushanses

2022-04-19 07:42 UTC, Magnus93 requested changes

2022-04-19 07:42 UTC, Magnus93 commented on Settlement/newFee.ts
> +export type newFee = {
Should have uppercase `N` in `NewFee`.

Alternative:
Put the old `Fee` type in a folder called `V1` So old fee could be referred to as `Settlement.V1.Fee` and this fee could be `Settlement.Fee`

2022-04-20 07:28 UTC, marcushanses commented on Settlement/newFee.ts
> +export type newFee = {
https://github.com/intergiro/model-acquirer/pull/306/commits/237c31dfc4a32a9a32b8ed6f2abc969b653df869

2022-04-20 15:41 UTC, robinnedergard requested changes
EDIT: FIXED!

original message:
On a capture test I got this weird change in test results in worker-settlement when testing with this branch. Do you know what it might be caused by? A quick check makes me think that all/many scheme/interchange fees might be reversed in the test results?
```
- Expected  - 4
+ Received  + 4

"fee": Object {
    -         "scheme": 12,
    +         "interchange": -12,
    +         "intergiro": 61.99,
    +         "network": 0,
              "total": 49.99,
            },
```

2022-04-20 15:53 UTC, robinnedergard requested changes

2022-04-20 15:53 UTC, robinnedergard commented on Settlement/Fee.ts
> +				intergiro: value.scheme,
Wrong, should be:
```
interchange: value.scheme,
intergiro: value.total - value.scheme,
```
Also use isoly.Currency.subtract() in this case as we don't have more than currency dependant decimals in this case.

2022-04-21 07:01 UTC, marcushanses commented on Settlement/Fee.ts
> +				intergiro: value.scheme,
Ah, thank you for noticing!

2022-04-22 15:02 UTC, robinnedergard approved these changes

2022-04-25 06:07 UTC, fredrikbryntesson approved these changes

2022-04-25 06:07 UTC, merged