Processor suggestion
intergiro/model-acquirer pull request #315
Opened 2022-04-25 15:21 UTC by marcushanses

2022-04-26 07:35 UTC, nilssonemma commented on Authorization/Processor/Baboba.ts
> +			mid: "string",
Do we really need this for baboba? Since the processor field is optional, we could leave it empty for transactions through baboba

2022-04-26 08:13 UTC, marcushanses commented on Authorization/Processor/Baboba.ts
> +			mid: "string",
Sure, I though it made sense to simulate a real processor.

2022-04-26 12:26 UTC, asnahassan approved these changes

2022-04-27 07:15 UTC, Magnus93 requested changes

2022-04-27 07:15 UTC, Magnus93 commented on Authorization/Processor/Silverflow.ts
> +				code: value.authorizationIsoFields.responseCodeDescription,
```suggestion
				code: value.authorizationIsoFields.responseCode
```

2022-04-27 07:21 UTC, Magnus93 requested changes

2022-04-27 07:21 UTC, Magnus93 commented on Authorization/Processor/Ipg.ts
> +				code: value.processor.responseMessage,
```suggestion
				code: value.processor.responseCode,
```
There are apparently to separate `Issuer Response...`, I was also mixing them up
![image](https://user-images.githubusercontent.com/14332757/165463417-2b34d364-346c-4371-89a0-b51548035326.png)

2022-04-27 08:59 UTC, nilssonemma requested changes

2022-04-27 08:59 UTC, nilssonemma commented on Authorization/Processor/Silverflow.ts
> +				code: value.authorizationIsoFields.responseCode
```suggestion
				code: value.authorizationIsoFields.responseCode,
```

2022-04-28 07:37 UTC, Magnus93 approved these changes

2022-04-28 12:19 UTC, nilssonemma approved these changes

2022-04-28 22:24 UTC, fredrikbryntesson approved these changes

2022-04-28 22:24 UTC, merged