Settlement toCsv restructure and Settlement.Metabase export + type
intergiro/model-acquirer pull request #319
Opened 2022-04-27 11:58 UTC by robinnedergard

2022-04-28 07:35 UTC, Magnus93 requested changes

2022-04-28 07:35 UTC, Magnus93 commented on Settlement/index.ts
> +		costPlus?: true | undefined
`undefined` is redundant
```suggestion
		role?: "merchant" | "agent" | "master",
		costPlus?: true
```

2022-04-28 07:38 UTC, robinnedergard commented on Settlement/index.ts
> +		costPlus?: true | undefined
Done

2022-04-28 07:42 UTC, marcushanses approved these changes

2022-04-28 08:09 UTC, Magnus93 approved these changes

2022-04-28 13:29 UTC, nilssonemma approved these changes

2022-04-29 11:55 UTC, marcushanses reviewed
Please resolve circular dependencies.
I think that an is function for the type acquirer.Settlement.Metabase would be neat.

2022-05-01 22:09 UTC, fredrikbryntesson approved these changes

2022-05-01 22:10 UTC, merged