Clean up
intergiro/model-acquirer pull request #331
Opened 2022-05-05 15:03 UTC by Magnus93

2022-05-05 15:04 UTC, nilssonemma approved these changes

2022-05-05 15:23 UTC, robinnedergard requested changes
Add parity

2022-05-09 07:30 UTC, Magnus93 commented
> Add parity

#332

2022-05-09 13:24 UTC, Magnus93 commented on Settlement/conversion/detailed/toCsv.ts
> +		...csv.data.map((line: Settlement | Complete | Agent | CostPlus | Merchant | Master) =>
This needs to be added otherwise `merchant-ui` complains.

2022-05-10 08:18 UTC, robinnedergard approved these changes

2022-05-10 08:58 UTC, fredrikbryntesson approved these changes

2022-05-10 08:58 UTC, merged