Merchant processor parity
intergiro/model-acquirer pull request #335
Opened 2022-05-23 14:00 UTC by asnahassan

Add processor.get() function in model-acquirer which were visa and mastercard.

2022-05-24 09:59 UTC, robinnedergard requested changes
Remember to change is and flaw as in the master branch based PR

2022-05-30 07:41 UTC, nilssonemma approved these changes

2022-05-30 09:36 UTC, Magnus93 requested changes

2022-05-30 09:36 UTC, Magnus93 commented on Merchant/index.ts
> +		processor: "omnipay" | "ipg" | "silverflow" | "baboba",
Add case for `"clearhaus"`

2022-05-30 09:47 UTC, asnahassan commented on Merchant/index.ts
> +		processor: "omnipay" | "ipg" | "silverflow" | "baboba",
Fixed

2022-05-30 11:26 UTC, marcushanses approved these changes

2022-05-30 13:40 UTC, fredrikbryntesson approved these changes

2022-05-30 13:41 UTC, merged