Added a processor.get for visa and mastercard.
intergiro/model-acquirer pull request #336
Opened 2022-05-23 14:03 UTC by asnahassan

Add processor.get() function in model-acquirer which were visa and mastercard.

2022-05-24 09:16 UTC, robinnedergard requested changes

2022-05-24 09:16 UTC, robinnedergard commented on Merchant/Processor.ts
> +	clearhaus?: { reference: string }
We have to have a merchant specific key, that won't be specified in the key for our acquirer:
```suggestion
	clearhaus?: { 
	reference: string
	key: string 
	}
```

2022-05-25 07:31 UTC, robinnedergard requested changes

2022-05-25 07:31 UTC, robinnedergard commented on Merchant/index.ts
> +				(MerchantProcessor.is(value.processor.visa) && MerchantProcessor.is(value.processor.mastercard)))
You are accessing a property (value.processor) that may not even be an object, which could result in a crash if it is a string or simular.
```suggestion
				(typeof value.processor == "object" && value.processor &&
				MerchantProcessor.is(value.processor.visa) && MerchantProcessor.is(value.processor.mastercard)))
```

2022-05-25 07:31 UTC, robinnedergard commented on Merchant/index.ts
> +								(MerchantProcessor.is(value.processor.visa) && MerchantProcessor.is(value.processor.mastercard)) || {
```suggestion
								(MerchantProcessor.is(value.processor.visa) && MerchantProcessor.is(value.processor.mastercard)) || {
```

2022-05-25 07:31 UTC, robinnedergard commented on Merchant/index.ts
> +								(MerchantProcessor.is(value.processor.visa) && MerchantProcessor.is(value.processor.mastercard)) || {
```suggestion
								(typeof value.processor == "object" && value.processor &&
								MerchantProcessor.is(value.processor.visa) && MerchantProcessor.is(value.processor.mastercard)) || {
```

2022-05-25 07:31 UTC, robinnedergard commented on Merchant/index.ts
> +								(MerchantProcessor.is(value.processor.visa) && MerchantProcessor.is(value.processor.mastercard)) || {
```suggestion
								(typeof value.processor == "object" && value.processor &&
								MerchantProcessor.is(value.processor.visa) && MerchantProcessor.is(value.processor.mastercard)) || {
```

2022-05-26 14:01 UTC, nilssonemma approved these changes

2022-05-30 09:19 UTC, Magnus93 requested changes

2022-05-30 09:19 UTC, Magnus93 commented on Merchant/index.ts
> +		processor: "omnipay" | "ipg" | "silverflow" | "baboba",
Add case for `"clearhaus"` (`merchantProcessor?.clearhaus.reference`)

2022-05-30 09:33 UTC, asnahassan commented on Merchant/index.ts
> +		processor: "omnipay" | "ipg" | "silverflow" | "baboba",
Fixed

2022-05-30 09:50 UTC, Magnus93 approved these changes

2022-05-30 11:34 UTC, marcushanses approved these changes

2022-05-30 12:57 UTC, fredrikbryntesson approved these changes

2022-05-30 12:58 UTC, merged

2022-06-09 20:45 UTC, simonmika commented on Merchant/index.spec.ts
> +					type: "undefined | Processor | { visa: Processor; mastercard: Processor } ",
Should use recursive flaws call.