Added function to get processor name.
intergiro/model-acquirer pull request #347
Opened 2022-06-07 17:33 UTC by nilssonemma

- [x] https://github.com/intergiro/model-acquirer/pull/345

2022-06-08 06:58 UTC, asnahassan approved these changes

2022-06-08 07:09 UTC, marcushanses approved these changes

2022-06-13 07:25 UTC, Magnus93 approved these changes

2022-06-13 07:29 UTC, Magnus93 requested changes

2022-06-13 07:29 UTC, Magnus93 commented on Merchant/index.ts
> +		const processor = scheme == "mastercard" || scheme == "visa" ? Merchant.getProcessor(merchant, scheme) : undefined
This will always return `undefined` if `scheme` is not set.
`getProcessor` could still be called without scheme.

2022-06-13 07:36 UTC, Magnus93 approved these changes

2022-06-13 07:53 UTC, merged