Added function to get processor name.
intergiro/model-acquirer pull request #348
Opened 2022-06-07 17:34 UTC by nilssonemma

https://github.com/intergiro/model-acquirer/pull/346

2022-06-08 06:58 UTC, asnahassan approved these changes

2022-06-08 07:08 UTC, marcushanses approved these changes

2022-06-09 13:10 UTC, Magnus93 requested changes

2022-06-09 13:10 UTC, Magnus93 commented on Merchant/index.ts
> +	}
Add `"clearhaus"` and rebase to make only your changes visible on PR.

2022-06-13 07:33 UTC, Magnus93 requested changes

2022-06-13 07:33 UTC, Magnus93 commented on Merchant/index.ts
> +		const processor = scheme == "mastercard" || scheme == "visa" ? Merchant.getProcessor(merchant, scheme) : undefined
`processor` is always undefined if `scheme` is undefined,
Can still call `getProcessor` with undefined `scheme`

2022-06-13 07:37 UTC, Magnus93 approved these changes

2022-06-13 07:53 UTC, merged