Creatable safe test
intergiro/model-acquirer pull request #356
Opened 2022-06-29 09:11 UTC by asnahassan

Created tests for creatable test card.

2022-07-06 07:26 UTC, nilssonemma approved these changes

2022-07-06 07:58 UTC, Magnus93 requested changes
You seem to have 2 identical test files, testing the same things. Remove one of them.

2022-07-06 07:58 UTC, Magnus93 commented on Verification/Creatable/index.spec.ts
> +				scheme: "viDDsa",
Incorrect spelling on `scheme` as well, so this test does not prove more then the previous test.
Fix `scheme` spelling on this test

2022-07-08 14:07 UTC, Magnus93 requested changes

2022-07-08 14:07 UTC, Magnus93 commented on Verification/Creatable/Safe.spec.ts
> +				scheme: "viDDsa",
The spelling of scheme is wrong here just like in the previous test. SO this test does not prove anything more than the previous test.

**Fix `scheme` spelling.**

2022-07-11 06:57 UTC, asnahassan commented on Verification/Creatable/Safe.spec.ts
> +				scheme: "viDDsa",
Fixed

2022-08-01 09:13 UTC, Magnus93 approved these changes

2022-08-01 09:13 UTC, merged