Created Creatable.Safe types for Authorization and Verification
intergiro/model-acquirer pull request #357
Opened 2022-06-29 09:13 UTC by nilssonemma

2022-06-29 11:30 UTC, robinnedergard requested changes

2022-06-29 11:30 UTC, robinnedergard commented on Authorization/Creatable/Safe/Card.ts
> +	csc?: "matched" | "mismatched" | "present"
Where are we supposed to put the "magic string" with the token if they have same property names?

2022-07-01 08:01 UTC, asnahassan approved these changes

2022-07-05 12:55 UTC, Magnus93 requested changes

2022-07-05 12:55 UTC, Magnus93 commented on package.json
> +    "@payfunc/model-card": "0.2.42",
There is a newer version
```suggestion
    "@payfunc/model-card": "0.2.43",
```

2022-07-05 12:55 UTC, Magnus93 commented on Authorization/Creatable/index.ts
> +		return result // Todo: Clean up function
I did not found any way you can change this without making it more complicated. Typescript is just stupid sometimes.

**Remove comment**

2022-07-05 12:55 UTC, Magnus93 commented on Verification/Creatable/Base.ts
> +			typeof value.number == "string" &&
```suggestion
			typeof value == "object" && 
			value &&
			typeof value.number == "string" &&
```

2022-07-05 12:55 UTC, Magnus93 commented on Verification/Creatable/Base.ts
> +					typeof value.response.type == "string" &&
```suggestion
				(typeof value.response == "object" &&
				value.response &&
					typeof value.response.type == "string" &&
```

2022-07-05 12:55 UTC, Magnus93 commented on Authorization/Creatable/Base.ts
> +			(value.id == undefined || authly.Identifier.is(value.id, 16)) &&
```suggestion
			typeof value == "object" &&
			value &&
			(value.id == undefined || authly.Identifier.is(value.id, 16)) &&
```

2022-07-05 14:50 UTC, merged