Add number to all State.Authorization.items
intergiro/model-acquirer pull request #389
Opened 2022-09-08 15:22 UTC by Magnus93

2022-09-08 15:48 UTC, robinnedergard approved these changes

2022-09-09 08:26 UTC, nilssonemma requested changes

2022-09-09 08:26 UTC, nilssonemma commented on State/FailedAuthorization.ts
> +				Items.from(value.authorization.items)) &&
```suggestion
				Items.is(value.authorization.items)) &&
```

2022-09-09 08:26 UTC, nilssonemma commented on State/Authorization.ts
> +				Items.from(value.authorization.items)) &&
```suggestion
				Items.is(value.authorization.items)) &&
```

2022-09-09 08:40 UTC, nilssonemma approved these changes

2022-09-09 14:45 UTC, fredrikbryntesson approved these changes

2022-09-09 14:45 UTC, merged