Removed Items from authorization creatable.
intergiro/model-acquirer pull request #424
Opened 2022-10-24 09:56 UTC by marcushanses

2022-10-24 13:55 UTC, nilssonemma requested changes

2022-10-24 13:55 UTC, nilssonemma commented on Authorization/Creatable/Base.ts
> +			!value.amount != !value.items &&
This logic is already written above

2022-10-24 13:55 UTC, nilssonemma commented on Authorization/index.ts
>  	amount: number
Please update is and flaw function in this file

2022-10-24 13:55 UTC, nilssonemma commented on State/Authorization.ts
> +				amount: state.authorization.amount ?? Items.from(state.authorization.items),
Is there a reason items is not removed from the state?

2022-10-24 13:57 UTC, nilssonemma commented on Authorization/Creatable/Base.ts
> +			!value.amount != !value.items &&
By "this logic" I mean where you check that only one of items/amount is assigned

2022-10-24 14:15 UTC, nilssonemma commented
Please also update to latest prettierx/eslint to fix audit error

2022-10-24 16:16 UTC, nilssonemma requested changes

2022-10-24 16:16 UTC, nilssonemma commented on Authorization/Creatable/Base.ts
> +			!value.amount != !value.items &&
```suggestion
```

2022-10-25 07:22 UTC, marcushanses commented on Authorization/Creatable/Base.ts
> +			!value.amount != !value.items &&
I realized this check will not work for 0 amounts.

2022-10-25 07:27 UTC, nilssonemma approved these changes

2022-10-25 07:28 UTC, merged